services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hello
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      